spring.application.name=project1

#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=dev

server.address=0.0.0.0
server.port=8080